exports.global = {
  years: [
    2002, 
    2003, 2004, 2005,
    2006, 2007, 2008, 2009,
    2010, 2011, 2012, 2013,
    2014, 2015, 2016, 2017,
    2018, 2019, 2020, 2021
  ],
  rawDataPath: './data/raw',
  parsedDataPath: './data/parsed',
  finalParsedDataPath: './data/parsed/final',
  enrichedDataPath: './data/enriched',
  nvdUrl: 'https://nvd.nist.gov/vuln/detail',
  cveUrl: 'https://cve.mitre.org/cgi-bin/cvename.cgi',
  refrensesConfig: {
    "securityfocus.com": { symbol: "a" },
    "exchange.xforce.ibmcloud.com": { symbol: "b" },
    "securitytracker.com": { symbol: "c" },
    "github.com": { symbol: "d" },
    "debian.org": { symbol: "e" },
    "security.gentoo.org": { symbol: "f" },
    "ubuntu.com": { symbol: "g" },
    "kb.cert.org": { symbol: "h" },
    "bugzilla.redhat.com": { symbol: "i" },
    "lists.apple.com": { symbol: "j" },
    "usn.ubuntu.com": { symbol: "k" },
    "portal.msrc.microsoft.com": { symbol: "l" },
    "docs.microsoft.com": { symbol: "m" },
    "bugzilla.mozilla.org": { symbol: "n" },
    "mozilla.org": { symbol: "o" },
    "security.netapp.com": { symbol: "p" },
    "jvn.jp": { symbol: "q" },
    "drupal.org": { symbol: "r" },
    "git.kernel.org": { symbol: "s" },
    "ics-cert.us-cert.gov": { symbol: "t" },
    "crbug.com": { symbol: "u" },
    "gentoo.org": { symbol: "v" },
    "talosintelligence.com": { symbol: "w" },
    "support.f5.com": { symbol: "x" },
  }
}
